#!/bin/sh

fancy_echo() {
	local fmt="$1"; shift

	# shellcheck disable=SC2059
	printf "\n$fmt\n" "$@"
}

append_to_bashrc() {
  local text="$1" bashrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.bash_profile" ]; then
    bashrc="$HOME/.bash_profile"
  else
    bashrc="$HOME/.bashrc"
  fi

  if ! grep -Fqs "$text" "$bashrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >> "$bashrc"
    else
      printf "\n%s\n" "$text" >> "$bashrc"
    fi
  fi
}

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/work/svn/maven/" ]; then
  mkdir -p "$HOME/work/svn/maven/"
fi

if [ ! -d "$HOME/work/git/maven/" ]; then
  mkdir -p "$HOME/work/git/maven/"
fi

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

update_shell() {
  local shell_path;
  shell_path="$(which bash)"

  fancy_echo "Changing your shell to bash ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    fancy_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

case "$SHELL" in
  */bash)
    if [ "$(which bash)" != '/bin/bash' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
  fi
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_bashrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_bashrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --verbose --file=- <<EOF
tap "homebrew/services"
tap "caskroom/cask"
tap "caskroom/versions"

# Unix
brew "bash-completion"
brew "term"
brew "git"
brew "subversion", args: ["with-java"]
brew "openssl"
brew "watchman"

# Heroku
brew "heroku"

# Programming language prerequisites and package managers
brew "libyaml" # should come after openssl
brew "yarn", args: ["--without node"]
brew "nvm"
cask "java8"
brew "maven"
brew "ant"

# Servers
brew "tomcat@8"

# Databases
brew "postgres", restart_service: :changed
brew "mongo", restart_service: :changed
brew "elasticsearch", restart_service: :changed

# Other tools
EOF

# for bash completion
fancy_echo "Adding bash completion details to bashrc..."
append_to_bashrc "[ -f $HOMEBREW_PREFIX/etc/bash_completion ] && . $HOMEBREW_PREFIX/etc/bash_completion"

# for nvm
fancy_echo "Adding nvm details to bashrc..."
append_to_bashrc 'export NVM_DIR="$HOME/.nvm"'
append_to_bashrc 'source $(brew --prefix nvm)/nvm.sh' 1

# setup node v7.0.0 for WSI
nvm install v7.0.0
nvm alias default v7.0.0

# finish Maven/Ant setup
fancy_echo "Increasing the Java heap space..."
append_to_bashrc 'export MAVEN_OPTS="-Xmx2048m -Xms512m -XX:MaxPermSize=512m"'
fancy_echo "Install Maven Ant-tasks plugin..."
if [ ! -f "$HOME/.ant/lib/maven-ant-tasks-2.1.3.jar" ]; then
  if [ ! -d "$HOME/.ant/lib" ]; then
    mkdir -p "$HOME/.ant/lib"
  fi
  curl -o ~/.ant/lib/maven-ant-tasks-2.1.3.jar http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
fi
if [ $(md5 -q ~/.ant/lib/maven-ant-tasks-2.1.3.jar) != "7ce48382d1aa4138027a58ec2f29beda" ]; then
  fancy_echo "Maven Ant-tasks plugin was NOT successfully installed"
fi
if [ ! -f "$HOME/.subversion/config" ]; then
  fancy_echo "Adding SVN AutoProps Configurations..."
  cd ~/work/svn
  svn checkout https://repos.wsgc.com/svn/core/setup/
  mv ~/work/svn/setup/config ~/.subversion/config
fi
if [ ! -d "$HOME/.m2" ]; then
    mkdir -p "$HOME/.m2"
fi
if [ ! -f "$HOME/.m2/settings.xml" ]; then
  fancy_echo "Copy WSI maven settings to local..."
  mv ~/work/svn/setup/maven/settings.xml ~/.m2/settings.xml
fi

append_to_bashrc "export ANT_HOME=$(brew --prefix ant)" 1
append_to_bashrc "export M2_HOME=$(brew --prefix maven)" 1
append_to_bashrc 'export M2="$M2_HOME/bin"' 1
append_to_bashrc "export MAVEN_OPTS=\"-Xmx2048m -Xms512m -Dorg.apache.maven.user-settings=$HOME/work/svn/setup/maven/settings.xml -Djava.net.preferIPv4Addresses=true\"" 1
append_to_bashrc "export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home" 1
append_to_bashrc "export CATALINA_BASE=$(brew --prefix tomcat@8)/libexec" 1
append_to_bashrc 'export CATALINA_HOME="$CATALINA_BASE"' 1
append_to_bashrc "export CATALINA_TMPDIR=$CATALINA_BASE/temp" 1
append_to_bashrc "export QAPP_CONF_DIR=$CATALINA_BASE/conf" 1

append_to_bashrc 'export PATH="$ANT_HOME/bin:$PATH"' 1
append_to_bashrc 'export PATH="$M2:$PATH"' 1
append_to_bashrc 'export PATH="$JAVA_HOME/bin:$PATH"' 1
append_to_bashrc 'export PATH="$PATH:~/temp"' 1

fancy_echo "Update heroku binary..."
brew unlink heroku
brew link --force heroku

if ! command -v rbenv >/dev/null; then
  if ! command -v rvm >/dev/null; then
    fancy_echo "Installing RVM and the latest Ruby..."
    curl -sSL https://get.rvm.io | bash -s stable --ruby --auto-dotfiles --autolibs=enable
    . ~/.rvm/scripts/rvm
  else
    local_version="$(rvm -v 2> /dev/null | awk '$2 != ""{print $2}')"
    latest_version="$(curl -s https://raw.githubusercontent.com/wayneeseguin/rvm/stable/VERSION)"
    if [ "$local_version" != "$latest_version" ]; then
      fancy_echo "Upgrading RVM..."
      rvm get stable --auto-dotfiles --autolibs=enable --with-gems="bundler"
    else
      fancy_echo "Already using the latest version of RVM. Skipping..."
    fi
  fi
fi

gem update --system
gem_install_or_update 'bundler'
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

gem_install_or_update 'saas'

if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi

fancy_echo "Cleaning up old Homebrew formulae ..."
brew cleanup
brew cask cleanup
